version: '3.9'

services:
  web:
    build:
      context: ./carMaintenance
    volumes:
      - static_data:/djangoBackend/vol/web
    expose:
     - 8000
    depends_on:
      - database
  
  nginx:
    build:
      context: ./nginx
    volumes:
      - static_data:/vol/static
    ports:
      - "8080:8080"
    depends_on:
      - web

  database:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - database_variables.env
      
volumes:
  static_data:
  postgres_data:
